### ISSUE TITLE
ALl .cpp not working unable to terminate

### ISSUE THREAD

**Issue by allowdoc** [p1d3er/KillEverything#2]
C:\Users\Administrator>C:\Users\Administrator\Downloads\Spiderkiller.exe start
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Driver initialized successfully.

**Comment by p1d3er** [comment]
SysMon has problems, and the other ones need to be tested according to the system version

**Comment by allowdoc** [comment]
i tried same as you video is ther need to load the .sys file i created using sc command to add the .sys file to service adn started but wehn i am running
C:\Users\Administrator>C:\Users\Administrator\Downloads\Spiderkiller.exe start
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Spiderkiller Start.
[+] Driver initialized successfully.

is gives this output and exit the program not killing  after this starge exist
[+] Driver initialized successfully.

i treid all methods my device is win10 even tested on win10 server
