### ISSUE TITLE
能说说安装驱动 怎么过360么

### ISSUE THREAD

**Issue by Summe7** [p1d3er/KillEverything#4]

**Comment by Summe7** [comment]
![捕获](https://github.com/user-attachments/assets/c719e4d5-d2ae-4ba1-a233-dd5572f50eb7)

**Comment by Zer08Bytes** [comment]
[Summe7](https://github.com/Summe7)    你有加载驱动的代码吗？

**Comment by Summe7** [comment]
cmd 命令可以加载 @Zer08Bytes

**Comment by Summe7** [comment]
不过 一样 过不了 360

**Comment by Zer08Bytes** [comment]
cmd加载驱动？？？ 我是写程序加载的，可以成功。当然，360拦截驱动加载行为

**Comment by Summe7** [comment]
@Zer08Bytes 能分享一下吗

**Comment by Zer08Bytes** [comment]
过不了360哈  @Summe7

**Comment by p1d3er** [comment]
使用 NtLoadDriver 加载
